### ISSUE TITLE
Schema error Fedora 34

### ISSUE THREAD

**Issue by enogs** [hardpixel/dash-to-plank#7] opened 2021-04-28 04:07 UTC
Trying to run the extension, no luck. In the extensions application the following message is displayed 

**"Plank schema not found. Please check your installation."**

**Comment by jonian** [comment] 2021-04-28 08:21
Did you check that plank works without the extension?

**Comment by ivnmad** [comment] 2021-04-28 08:41
I installed both Plank and the extension (Fedora 34], but it doesn't seem to work.
Does it work with Wayland? Or X11 only?

If I try to run Plank by itself (from terminal) I get the following error:
"[CRITICAL 09:38:01.133821] [AbstractMain:255] Only X11 environments are supported."

**Comment by jonian** [comment] 2021-04-28 08:43
@ivnmad, X11 only. Plank does not work on wayland, so the extension does not work on wayland. I will add it in the description to avoid confusion.

https://bugs.launchpad.net/plank/+bug/1632841

**Comment by jyotirmaybarman** [comment] 2021-04-28 08:52
Running `sudo plank`  It is working.
But it generates this warnings -
`[WARN 14:22:53.458231] [Environment:165] XDG_SESSION_CLASS not set in this environment!
[WARN 14:22:53.458248] [Environment:183] Neither of XDG_SESSION_DESKTOP, XDG_CURRENT_DESKTOP or DESKTOP_SESSION is set in this environment!
[WARN 14:22:53.458254] [Environment:196] XDG_SESSION_TYPE not set in this environment!
[WARN 14:22:53.544471] [Environment:183] Neither of XDG_SESSION_DESKTOP, XDG_CURRENT_DESKTOP or DESKTOP_SESSION is set in this environment!
[WARN 14:22:53.546734] [SessionManager:60] Error registering client: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.SessionManager was not provided by any .service files
[WARN 14:22:53.546756] [Main:84] Failed to register with Session manager`

**Comment by enogs** [comment] 2021-04-28 13:05
> Did you check that plank works without the extension?

Yes works well alone

**Comment by jonian** [comment] 2021-04-28 13:26
@enogs if you enable the extension while plank is running, does the extension work?

**Comment by jonian** [comment] 2021-04-28 13:28
@enogs please provide info for:

- GNOME Shell version
- Dash to Plank version
- Output of `journalctl -g plank`

**Comment by jonian** [comment] 2021-04-28 13:50
@JyotirmayBarman you should **not** run plank with sudo. Something is wrong with your installation if you can't start plank as normal user. Make sure you are on X11, plank does not support Wayland.

**Comment by jyotirmaybarman** [comment] 2021-04-29 13:47
Yes, In X11 it is working fine.

**Comment by kassim3** [comment] 2021-06-06 14:09
I was getting the same issue. I reloaded gnome and it worked

**Comment by jonian** [comment] 2021-10-10 14:04
Closing as I can't reproduce the error. Tried in a fresh fedora install.

**Closed as completed by jonian** 2021-10-10 14:04 UTC
